steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/braided-city-406614/gcp-devops/gcp-python', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', asia-south1-docker.pkg.dev/braided-city-406614/gcp-devops/gcp-python]
# dummy commit
 