apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-app
  name: python-app
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/braided-city-406614/gcp-devops/gcp-python
        name: python-app
        ports:
        - containerPort: 5000

--- 
apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: prod
spec:
  selector:
    app: python-app
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer
        